name: deploy

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true

      # https://benlimmer.com/2024/04/08/caching-cdk-dockerimageasset-github-actions/
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # - name: Update rust
      #   run: rustup update

      # - name: Build
      #   run: cargo build --verbose
      #   working-directory: ./solver

      # - name: Run tests
      #   run: cargo test --verbose
      #   working-directory: ./solver

      - name: Setup NPM dependencies
        run: npm ci
        working-directory: ./infra

      - name: Deploy
        run: npm run cdk deploy -- --require-approval never
        working-directory: ./infra
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # API_TOKEN: ${{ secrets.API_TOKEN }}
